"use client";

import React, { useEffect } from "react";
import { Inter } from "next/font/google";
import SideNav from "@/components/SideNav";
import "./globals.css";
import Login from "./Login/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const authToken = localStorage.getItem("authToken");
  const isAuthenticated = !!authToken;

  useEffect(() => {
    if (!isAuthenticated && window.location.pathname !== "/Login") {
      window.location.href = "/Login";
    }
    if (isAuthenticated && window.location.pathname === "/Login") {
      window.location.href = "/";
    }
  }, []);

  if (typeof window === "undefined") {
    // const authToken = localStorage.getItem("authToken");
    // const isAuthenticated = !!authToken;
    return null;
  }

  return (
    <html lang="en">
      <body className={`flex bg-red-50 ${inter.className} `}>
        {isAuthenticated ? (
          <>
            <SideNav />
            {children}
          </>
        ) : (
          <Login /> 
        )}
      </body>
    </html>
  );
}
